// USER REDUCER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

//UI REDUCER TYPES
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_DATA = "LOADING_DATA";

//DATA REDUCER TYPES

export const SET_RIFTS = "SET_RIFTS";
export const SET_RIFT = "SET_RIFT";
export const LIKE_RIFT = "LIKE_RIFT";
export const UNLIKE_RIFT = "UNLIKE_RIFT";
export const DELETE_RIFT = "DELETE_RIFT";
