// USER REDUCER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";
//UI REDUCER TYPES
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_DATA = "LOADING_DATA";

//DATA REDUCER TYPES
export const SET_RIFTS = "SET_RIFTS";
export const SET_RIFT = "SET_RIFT";
export const LIKE_RIFT = "LIKE_RIFT";
export const UNLIKE_RIFT = "UNLIKE_RIFT";
export const DELETE_RIFT = "DELETE_RIFT";
export const POST_RIFT = "POST_RIFT";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
